/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppRouteRouteImport } from './routes/_authenticated/app/route'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app/index'
import { Route as AuthenticatedAppSupportInboxRouteImport } from './routes/_authenticated/app/support-inbox'
import { Route as AuthenticatedAppSupportRouteImport } from './routes/_authenticated/app/support'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app/settings'
import { Route as AuthenticatedAppRidesRouteImport } from './routes/_authenticated/app/rides'
import { Route as AuthenticatedAppRewardsRouteImport } from './routes/_authenticated/app/rewards'
import { Route as AuthenticatedAppPassengerRouteImport } from './routes/_authenticated/app/passenger'
import { Route as AuthenticatedAppInsurerRouteImport } from './routes/_authenticated/app/insurer'
import { Route as AuthenticatedAppDriverRouteImport } from './routes/_authenticated/app/driver'
import { Route as AuthenticatedAppCompleteProfileRouteImport } from './routes/_authenticated/app/complete-profile'
import { Route as AuthenticatedAppAdminRouteImport } from './routes/_authenticated/app/admin'
import { Route as ApiPublicWebhooksTopupRouteImport } from './routes/api/public/webhooks/topup'
import { Route as AuthenticatedAppTicketTicketIdRouteImport } from './routes/_authenticated/app/ticket.$ticketId'
import { Route as AuthenticatedAppRideRideIdRouteImport } from './routes/_authenticated/app/ride.$rideId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRouteRoute = AuthenticatedAppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppSupportInboxRoute =
  AuthenticatedAppSupportInboxRouteImport.update({
    id: '/support-inbox',
    path: '/support-inbox',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppSupportRoute = AuthenticatedAppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppRidesRoute = AuthenticatedAppRidesRouteImport.update({
  id: '/rides',
  path: '/rides',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppRewardsRoute = AuthenticatedAppRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppPassengerRoute =
  AuthenticatedAppPassengerRouteImport.update({
    id: '/passenger',
    path: '/passenger',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppInsurerRoute = AuthenticatedAppInsurerRouteImport.update({
  id: '/insurer',
  path: '/insurer',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppDriverRoute = AuthenticatedAppDriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppCompleteProfileRoute =
  AuthenticatedAppCompleteProfileRouteImport.update({
    id: '/complete-profile',
    path: '/complete-profile',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppAdminRoute = AuthenticatedAppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const ApiPublicWebhooksTopupRoute = ApiPublicWebhooksTopupRouteImport.update({
  id: '/api/public/webhooks/topup',
  path: '/api/public/webhooks/topup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppTicketTicketIdRoute =
  AuthenticatedAppTicketTicketIdRouteImport.update({
    id: '/ticket/$ticketId',
    path: '/ticket/$ticketId',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppRideRideIdRoute =
  AuthenticatedAppRideRideIdRouteImport.update({
    id: '/ride/$rideId',
    path: '/ride/$rideId',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/app/admin': typeof AuthenticatedAppAdminRoute
  '/app/complete-profile': typeof AuthenticatedAppCompleteProfileRoute
  '/app/driver': typeof AuthenticatedAppDriverRoute
  '/app/insurer': typeof AuthenticatedAppInsurerRoute
  '/app/passenger': typeof AuthenticatedAppPassengerRoute
  '/app/rewards': typeof AuthenticatedAppRewardsRoute
  '/app/rides': typeof AuthenticatedAppRidesRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/support': typeof AuthenticatedAppSupportRoute
  '/app/support-inbox': typeof AuthenticatedAppSupportInboxRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/ride/$rideId': typeof AuthenticatedAppRideRideIdRoute
  '/app/ticket/$ticketId': typeof AuthenticatedAppTicketTicketIdRoute
  '/api/public/webhooks/topup': typeof ApiPublicWebhooksTopupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/admin': typeof AuthenticatedAppAdminRoute
  '/app/complete-profile': typeof AuthenticatedAppCompleteProfileRoute
  '/app/driver': typeof AuthenticatedAppDriverRoute
  '/app/insurer': typeof AuthenticatedAppInsurerRoute
  '/app/passenger': typeof AuthenticatedAppPassengerRoute
  '/app/rewards': typeof AuthenticatedAppRewardsRoute
  '/app/rides': typeof AuthenticatedAppRidesRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/support': typeof AuthenticatedAppSupportRoute
  '/app/support-inbox': typeof AuthenticatedAppSupportInboxRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/ride/$rideId': typeof AuthenticatedAppRideRideIdRoute
  '/app/ticket/$ticketId': typeof AuthenticatedAppTicketTicketIdRoute
  '/api/public/webhooks/topup': typeof ApiPublicWebhooksTopupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/_authenticated/app/admin': typeof AuthenticatedAppAdminRoute
  '/_authenticated/app/complete-profile': typeof AuthenticatedAppCompleteProfileRoute
  '/_authenticated/app/driver': typeof AuthenticatedAppDriverRoute
  '/_authenticated/app/insurer': typeof AuthenticatedAppInsurerRoute
  '/_authenticated/app/passenger': typeof AuthenticatedAppPassengerRoute
  '/_authenticated/app/rewards': typeof AuthenticatedAppRewardsRoute
  '/_authenticated/app/rides': typeof AuthenticatedAppRidesRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/app/support': typeof AuthenticatedAppSupportRoute
  '/_authenticated/app/support-inbox': typeof AuthenticatedAppSupportInboxRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/ride/$rideId': typeof AuthenticatedAppRideRideIdRoute
  '/_authenticated/app/ticket/$ticketId': typeof AuthenticatedAppTicketTicketIdRoute
  '/api/public/webhooks/topup': typeof ApiPublicWebhooksTopupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/confidentialite'
    | '/reset-password'
    | '/sitemap.xml'
    | '/app'
    | '/app/admin'
    | '/app/complete-profile'
    | '/app/driver'
    | '/app/insurer'
    | '/app/passenger'
    | '/app/rewards'
    | '/app/rides'
    | '/app/settings'
    | '/app/support'
    | '/app/support-inbox'
    | '/app/'
    | '/app/ride/$rideId'
    | '/app/ticket/$ticketId'
    | '/api/public/webhooks/topup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/confidentialite'
    | '/reset-password'
    | '/sitemap.xml'
    | '/app/admin'
    | '/app/complete-profile'
    | '/app/driver'
    | '/app/insurer'
    | '/app/passenger'
    | '/app/rewards'
    | '/app/rides'
    | '/app/settings'
    | '/app/support'
    | '/app/support-inbox'
    | '/app'
    | '/app/ride/$rideId'
    | '/app/ticket/$ticketId'
    | '/api/public/webhooks/topup'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/confidentialite'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/app'
    | '/_authenticated/app/admin'
    | '/_authenticated/app/complete-profile'
    | '/_authenticated/app/driver'
    | '/_authenticated/app/insurer'
    | '/_authenticated/app/passenger'
    | '/_authenticated/app/rewards'
    | '/_authenticated/app/rides'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/support'
    | '/_authenticated/app/support-inbox'
    | '/_authenticated/app/'
    | '/_authenticated/app/ride/$rideId'
    | '/_authenticated/app/ticket/$ticketId'
    | '/api/public/webhooks/topup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicWebhooksTopupRoute: typeof ApiPublicWebhooksTopupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/support-inbox': {
      id: '/_authenticated/app/support-inbox'
      path: '/support-inbox'
      fullPath: '/app/support-inbox'
      preLoaderRoute: typeof AuthenticatedAppSupportInboxRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/support': {
      id: '/_authenticated/app/support'
      path: '/support'
      fullPath: '/app/support'
      preLoaderRoute: typeof AuthenticatedAppSupportRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/rides': {
      id: '/_authenticated/app/rides'
      path: '/rides'
      fullPath: '/app/rides'
      preLoaderRoute: typeof AuthenticatedAppRidesRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/rewards': {
      id: '/_authenticated/app/rewards'
      path: '/rewards'
      fullPath: '/app/rewards'
      preLoaderRoute: typeof AuthenticatedAppRewardsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/passenger': {
      id: '/_authenticated/app/passenger'
      path: '/passenger'
      fullPath: '/app/passenger'
      preLoaderRoute: typeof AuthenticatedAppPassengerRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/insurer': {
      id: '/_authenticated/app/insurer'
      path: '/insurer'
      fullPath: '/app/insurer'
      preLoaderRoute: typeof AuthenticatedAppInsurerRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/driver': {
      id: '/_authenticated/app/driver'
      path: '/driver'
      fullPath: '/app/driver'
      preLoaderRoute: typeof AuthenticatedAppDriverRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/complete-profile': {
      id: '/_authenticated/app/complete-profile'
      path: '/complete-profile'
      fullPath: '/app/complete-profile'
      preLoaderRoute: typeof AuthenticatedAppCompleteProfileRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/admin': {
      id: '/_authenticated/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AuthenticatedAppAdminRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/api/public/webhooks/topup': {
      id: '/api/public/webhooks/topup'
      path: '/api/public/webhooks/topup'
      fullPath: '/api/public/webhooks/topup'
      preLoaderRoute: typeof ApiPublicWebhooksTopupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/ticket/$ticketId': {
      id: '/_authenticated/app/ticket/$ticketId'
      path: '/ticket/$ticketId'
      fullPath: '/app/ticket/$ticketId'
      preLoaderRoute: typeof AuthenticatedAppTicketTicketIdRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/ride/$rideId': {
      id: '/_authenticated/app/ride/$rideId'
      path: '/ride/$rideId'
      fullPath: '/app/ride/$rideId'
      preLoaderRoute: typeof AuthenticatedAppRideRideIdRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
  }
}

interface AuthenticatedAppRouteRouteChildren {
  AuthenticatedAppAdminRoute: typeof AuthenticatedAppAdminRoute
  AuthenticatedAppCompleteProfileRoute: typeof AuthenticatedAppCompleteProfileRoute
  AuthenticatedAppDriverRoute: typeof AuthenticatedAppDriverRoute
  AuthenticatedAppInsurerRoute: typeof AuthenticatedAppInsurerRoute
  AuthenticatedAppPassengerRoute: typeof AuthenticatedAppPassengerRoute
  AuthenticatedAppRewardsRoute: typeof AuthenticatedAppRewardsRoute
  AuthenticatedAppRidesRoute: typeof AuthenticatedAppRidesRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppSupportRoute: typeof AuthenticatedAppSupportRoute
  AuthenticatedAppSupportInboxRoute: typeof AuthenticatedAppSupportInboxRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppRideRideIdRoute: typeof AuthenticatedAppRideRideIdRoute
  AuthenticatedAppTicketTicketIdRoute: typeof AuthenticatedAppTicketTicketIdRoute
}

const AuthenticatedAppRouteRouteChildren: AuthenticatedAppRouteRouteChildren = {
  AuthenticatedAppAdminRoute: AuthenticatedAppAdminRoute,
  AuthenticatedAppCompleteProfileRoute: AuthenticatedAppCompleteProfileRoute,
  AuthenticatedAppDriverRoute: AuthenticatedAppDriverRoute,
  AuthenticatedAppInsurerRoute: AuthenticatedAppInsurerRoute,
  AuthenticatedAppPassengerRoute: AuthenticatedAppPassengerRoute,
  AuthenticatedAppRewardsRoute: AuthenticatedAppRewardsRoute,
  AuthenticatedAppRidesRoute: AuthenticatedAppRidesRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppSupportRoute: AuthenticatedAppSupportRoute,
  AuthenticatedAppSupportInboxRoute: AuthenticatedAppSupportInboxRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppRideRideIdRoute: AuthenticatedAppRideRideIdRoute,
  AuthenticatedAppTicketTicketIdRoute: AuthenticatedAppTicketTicketIdRoute,
}

const AuthenticatedAppRouteRouteWithChildren =
  AuthenticatedAppRouteRoute._addFileChildren(
    AuthenticatedAppRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRouteRoute: typeof AuthenticatedAppRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRouteRoute: AuthenticatedAppRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicWebhooksTopupRoute: ApiPublicWebhooksTopupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
